name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.4']

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          ini-values: date.timezone="Europe/London"

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      - name: Validate
        run: php vendor/bin/phpunit --coverage-text
